### ISSUE TITLE
make event routing configurable

### ISSUE THREAD

**Issue by rkuhn** [Actyx/Actyx#388]
Something like this:
```
  eventRouting:
    streams: # naming streams and configuring their retention policy
      metrics: # this is a stream name freely chosen by the admin
        maxSize: 10MB
        maxAge: 14d
        maxEvents: 4500
      logs:
        maxSize: 20MB
        maxAge: 3d
      cardreader:
        maxEvents: 100
        replication: false # other nodes are not interested in our readings
    routes:
    - from: "'metrics'"
      goto: metrics
    - from: "'log' & ('warn' | 'error')"
      # the default stream always exists (has number 0) and is permanent
      goto: default
    - from: "'log'"
      # all remaining logs go to ephemeral storage
      goto: logs
    - from: "'cardreader' & appId(com.actyx.cards)"
      goto: cardreader
```
The stream names need to be stored permanently in stream 0 as configuration events to avoid reusing stream numbers for different names as the config gets changed over time.
