### ISSUE TITLE
Configure event stream persistence policies

### ISSUE THREAD

**Issue by mhaushofer** [Actyx/Actyx#85]
### Problem to solve

When:

- configuring nodes with small disk space for a production installation

I want to:

- configure event streams to be ephemeral

So that:

- Events are deleted and I don't run out of disk space

### Acceptance criteria

- [ ] Stream persistence can be configured in node settings (array under `com.actyx/api/events/persistence`)
- [ ] Stream name is used for identification
- [ ] Maximum data size of event streams after compression can be configured in MB and GB
- [ ] Maximum number of events in an event stream can be configured
- [ ] Maximum age of events in an event stream can be configured in seconds, minutes, hours and days
- [ ] In case of multiple policies for the same stream, all policies are applied and whichever one is violated first leads to deletion of events
- [ ] The event with the smallest offset is deleted first
- [ ] A new persistence policy always applies to all events that are in the stream at time of reconfiguration:
   - [ ] If a stream is configured from ephemeral to persistent, no events are deleted anymore (= events that have already been emitted while that stream was ephemeral are not being deleted)
   - [ ] If a stream is configured from persistent to ephemeral, events that were emitted while the stream was configured persistent will be deleted at some point
- [ ] node settings disallow using the names `default`, `discovery` and `metrics`

Note: As the by Actyx automatically created streams 0, 1 and 2 do not have names, their retention policy can also not be configured.

### Example configuration

````yaml
persistence:
  example stream name:
     maxSize: 10MB # or e.g. 10GB
     maxAge: 14d # or e.g. 14s, 14m, 14h, 
     maxEvents: 10000
   example stream name 2:
     maxSize: 10MB
   example stream name: # already configured above, but technically this is still allowed
     maxAge: 7d
````
